### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by sckott** [ropensci/cartographer#18]
I tried to add travis file on different branch to send a PR, but the build failed as you require a certain version of `rgdal` and for some reason travis installs an older version https://travis-ci.org/ropensci/cartographer/builds/54587335#L1466 that's older than what's on CRAN http://cran.rstudio.com/web/packages/rgdal/ 

Not sure why there's such an old binary version of `rgdal`

**Comment by lmullen** [comment]
The Ubuntu packages for `libgdal-dev` (and maybe `libproj-dev`) are borked
and have been for months. I suspect that this is related to the older
version of `rgdal`. I'll see if I can replace the function that relies on
`rgdal` with a dependency on `geojsonio`.

**Comment by sckott** [comment]
Right now `geojsonio` still has `rgdal` in Imports https://github.com/ropensci/geojsonio/blob/master/DESCRIPTION#L21 - so I imagine you'd have the same problem?  I kinda want to remove `rgdal` cause it's such a pain, but maybe it makes sense to keep so that it's a one stop place for geojson io stuff

**Comment by lmullen** [comment]
`rgdal` is indeed a pain, but my difficulties with it have been mostly
because of the Ubuntu packages needed to build from source. If those are
ever cleared up I don't think it will be such a big issue.

On Mon, Mar 16, 2015 at 2:34 PM, Scott Chamberlain <notifications@github.com

**Comment by lmullen** [comment]
Trying a lower version of rgdal:
https://travis-ci.org/ropensci/cartographer/builds/54612901
