### ISSUE TITLE
travis failing

### ISSUE THREAD

**Issue by sckott** [ropensci/cartographer#22]
https://travis-ci.org/ropensci/cartographer/builds/55732157

not sure why...

**Comment by lmullen** [comment]
Thanks for the heads up. Gender also failed for no apparent reason, so I'm
going to restart both builds. I think it might be a Travis hiccup, but
we'll see.

**Comment by lmullen** [comment]
Appears just to have been a glitch with Travis.

**Comment by sckott** [comment]
cool cool
